
services:

  sessions-redis:
    command: [ "redis-server", "--save", "", "--appendonly", "no" ]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    image: redis:8.0.5-alpine
    mem_limit: 256mb
    networks:
      sessions:
        aliases:
          - sessions-redis.internal
    ports:
      - "6381:6379"
    volumes:
      - source: ./log/service/sessions-redis
        target: /log
        type: bind

  sessions-queue:
    command: [ "yarn", "workspace", "@tw050x.net.worker/sessions-queue", "exec", "node", "--inspect=0.0.0.0:9229", "artifact/run.js" ]
    depends_on:
      mongo-primary:
        condition: service_healthy
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD-SHELL", "test -f /healthcheck && grep -q '^healthy$' /healthcheck"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    image: tw050x.net.worker/sessions-queue:latest
    mem_limit: 512mb
    networks:
      sessions:
        aliases:
          - sessions.internal
      user: {}
    ports:
      - "9301:9229"
    pull_policy: never
    volumes:
      - source: ./.configs
        target: /srv/.configs
        type: bind
      - source: ./.secrets
        target: /srv/.secrets
        type: bind
      - source: ./library
        target: /srv/library
        type: bind
      - source: ./log/worker/sessions-queue
        target: /log
        type: bind
      - source: ./worker/sessions-queue
        target: /srv/worker/sessions-queue
        type: bind
      - source: ./tsconfig.json
        target: /srv/tsconfig.json
        type: bind
