
services:

  administration-service:
    command: [ "yarn", "workspace", "@tw050x.net/administration", "run", "nodemon", "--watch-path=/srv", "artifact/serve.js" ]
    # command: [ "tsx", "--inspect=0.0.0.0:9229", "--watch-path=/srv", "service/administration/serve.ts" ]
    depends_on:
      assets:
        condition: service_healthy
      authentication-service:
        condition: service_healthy
      localstack-service:
        condition: service_healthy
      mongo-database:
        condition: service_healthy
      traefik-router:
        condition: service_healthy
    env_file:
      - .env.administration
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/healthcheck || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    image: tw050x.net/administration:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.administration.entrypoints=websecure
      - traefik.http.routers.administration.rule=Host(`tw050x.dev`) && PathPrefix(`/admin/`)
      - traefik.http.routers.administration.tls=true
      - traefik.http.services.administration.loadbalancer.server.port=3000
    mem_limit: 200mb
    pull_policy: never
    volumes:
      - source: ./tsconfig.json
        target: /srv/tsconfig.json
        type: bind
      - source: ./library
        target: /srv/library
        type: bind
      - source: ./log/administration
        target: /log
        type: bind
      - source: ./service/administration
        target: /srv/service/administration
        type: bind

  assets:
    depends_on:
      traefik-router:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/assets/healthcheck.txt || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    image: tw050x.net/assets:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.assets.entrypoints=websecure
      - traefik.http.routers.assets.rule=Host(`tw050x.dev`) && PathPrefix(`/assets/`)
      - traefik.http.routers.assets.tls=true
      - traefik.http.services.assets.loadbalancer.server.port=3000
    mem_limit: 200mb
    pull_policy: never
    volumes:
      - source: ./assets/public
        target: /srv/assets/public
        type: bind

  authentication-service:
    command: [ "yarn", "workspace", "@tw050x.net/authentication", "run", "nodemon", "--watch-path=/srv", "artifact/serve.js" ]
    # command: [ "tsx", "--inspect=0.0.0.0:9229", "--watch-path=/srv", "service/authentication/serve.ts" ]
    depends_on:
      assets:
        condition: service_healthy
      localstack-service:
        condition: service_healthy
      mongo-database:
        condition: service_healthy
      traefik-router:
        condition: service_healthy
    env_file:
      - .env.authentication
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/healthcheck || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    image: tw050x.net/authentication:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.authentication.entrypoints=websecure
      - traefik.http.routers.authentication.rule=Host(`tw050x.dev`) && PathPrefix(`/login`)
      - traefik.http.routers.authentication.tls=true
      - traefik.http.services.authentication.loadbalancer.server.port=3000
    mem_limit: 200mb
    pull_policy: never
    volumes:
      - source: ./tsconfig.json
        target: /srv/tsconfig.json
        type: bind
      - source: ./library
        target: /srv/library
        type: bind
      - source: ./log/authentication
        target: /log
        type: bind
      - source: ./service/authentication
        target: /srv/service/authentication
        type: bind

  localstack-service:
    env_file:
      - .env.localstack
    # image: localstack/localstack
    image: gresau/localstack-persist:latest # don't trust this
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    volumes:
      - source: ./service/localstack/data
        target: /persisted-data
        type: bind
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind

  mongo-database:
    env_file:
      - .env.mongo
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    image: mongo:8.0.12
    ports:
      - 27017:27017
    restart: always
    volumes:
      - source: ./service/mongo/data
        target: /data/db
        type: bind

  marketing-service:
    command: [ "yarn", "workspace", "@tw050x.net/marketing", "run", "nodemon", "--watch-path=/srv", "artifact/serve.js" ]
    # command: [ "tsx", "--inspect=0.0.0.0:9229", "--watch-path=/srv", "service/marketing/serve.ts" ]
    depends_on:
      assets:
        condition: service_healthy
      localstack-service:
        condition: service_healthy
      mongo-database:
        condition: service_healthy
      traefik-router:
        condition: service_healthy
    env_file:
      - .env.marketing
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/healthcheck || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    image: tw050x.net/marketing:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.marketing.entrypoints=websecure
      - traefik.http.routers.marketing.rule=Host(`tw050x.dev`) && Path(`/`)
      - traefik.http.routers.marketing.tls=true
      - traefik.http.routers.marketing.priority=1
      - traefik.http.services.marketing.loadbalancer.server.port=3000
    mem_limit: 200mb
    pull_policy: never
    volumes:
      - source: ./tsconfig.json
        target: /srv/tsconfig.json
        type: bind
      - source: ./library
        target: /srv/library
        type: bind
      - source: ./log/marketing
        target: /log
        type: bind
      - source: ./service/marketing
        target: /srv/service/marketing
        type: bind

  traefik-router:
    image: traefik:v3.3.2
    depends_on:
      traefik-socket:
        condition: service_healthy
    env_file:
      - .env.traefik
    healthcheck:
      test: ["CMD-SHELL", "traefik healthcheck --ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-dashboard.entrypoints=websecure
      - traefik.http.routers.traefik-dashboard.rule=Host(`traefik.tw050x.dev`)
      - traefik.http.routers.traefik-dashboard.service=api@internal
      - traefik.http.routers.traefik-dashboard.tls=true
    mem_limit: 200mb
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./service/traefik/compose.traefik.toml:/etc/traefik/traefik.toml
      - ./service/traefik/certificates:/root/certificates

  traefik-socket:
    image: tecnativa/docker-socket-proxy:0.3.0
    env_file:
      - .env.traefik
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://localhost:2375/version || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    mem_limit: 200mb
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
