
services:
  users:
    command: [ "yarn", "workspace", "@tw050x.net.service/users", "exec", "node", "--inspect=0.0.0.0:9229", "--watch", "artifact/serve.js" ]
    depends_on:
      assets:
        condition: service_healthy
      error:
        condition: service_healthy
      mongo-primary:
        condition: service_healthy
      traefik:
        condition: service_healthy
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD-SHELL", "test -f /healthcheck && grep -q '^healthy$' /healthcheck"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    image: tw050x.net.service/users:latest
    labels:
      - traefik.docker.network=services
      - traefik.enable=true
      - traefik.http.routers.users.entrypoints=websecure
      - traefik.http.routers.users.middlewares=http-request-not-found-error@file
      - traefik.http.routers.users.rule=Host(`tw050x.dev`) && (Path(`/logout`) || Path(`/register`) || PathPrefix(`/login`) || PathPrefix(`/token/`) || PathPrefix(`/oauth2/`))
      - traefik.http.routers.users.tls=true
      - traefik.http.services.users.loadbalancer.server.port=3000
      - traefik.http.services.users.loadbalancer.server.scheme=https
      - traefik.http.services.users.loadbalancer.serversTransport=secure@file
    mem_limit: 512mb
    networks:
      mongo: {}
      sessions: {}
      services: {}
      users: {}
    ports:
      - "9206:9229"
    pull_policy: never
    volumes:
      - source: ./.configs
        target: /srv/.configs
        type: bind
      - source: ./.secrets
        target: /srv/.secrets
        type: bind
      - source: ./ca
        target: /srv/ca
        type: bind
      - source: ./library
        target: /srv/library
        type: bind
      - source: ./log/service/users
        target: /log
        type: bind
      - source: ./node_modules
        target: /srv/node_modules
        type: bind
      - source: ./service/users
        target: /srv/service/users
        type: bind
      - source: ./tsconfig.json
        target: /srv/tsconfig.json
        type: bind

  users-redis:
    command: [ "redis-server", "--save", "", "--appendonly", "no" ]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    image: redis:8.0.5-alpine
    mem_limit: 256mb
    networks:
      users:
        aliases:
          - users.network
    ports:
      - "6481:6379"
    volumes:
      - source: ./log/service/users-redis
        target: /log
        type: bind

  users-queue:
    command: [ "yarn", "workspace", "@tw050x.net.worker/users-queue", "exec", "node", "--inspect=0.0.0.0:9229", "--watch", "artifact/run.js" ]
    depends_on:
      mongo-primary:
        condition: service_healthy
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD-SHELL", "test -f /healthcheck && grep -q '^healthy$' /healthcheck"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    image: tw050x.net.worker/users-queue:latest
    mem_limit: 512mb
    networks:
      mongo:
        aliases:
          - mongo.network
      users: {}
    ports:
      - "9401:9229"
    pull_policy: never
    volumes:
      - source: ./.configs
        target: /srv/.configs
        type: bind
      - source: ./.secrets
        target: /srv/.secrets
        type: bind
      - source: ./library
        target: /srv/library
        type: bind
      - source: ./log/worker/users-queue
        target: /log
        type: bind
      - source: ./node_modules
        target: /srv/node_modules
        type: bind
      - source: ./worker/users-queue
        target: /srv/worker/users-queue
        type: bind
      - source: ./tsconfig.json
        target: /srv/tsconfig.json
        type: bind
