
services:

  user-service-queue:
    command: [ "yarn", "workspace", "@tw050x.net.worker/user-service-queue", "run", "nodemon", "--inspect=0.0.0.0:9229", "--watch", "/srv", "artifact/run.js" ]
    depends_on:
      mongo-primary:
        condition: service_healthy
    env_file:
      - .env.database.assignment
      - .env.database.user
      - .env.worker.user-service-queue
      - .env.workers.logs
      - .env.workers.mongo-client
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:3000/healthcheck || exit 1"]
    #   interval: 1m30s
    #   timeout: 30s
    #   retries: 5
    #   start_period: 30s
    image: tw050x.net.worker/user-service-queue:latest
    mem_limit: 512mb
    networks:
      - services
    ports:
      - "9301:9229"
    pull_policy: never
    volumes:
      - source: ./.configs
        target: /srv/.configs
        type: bind
      - source: ./.secrets
        target: /srv/.secrets
        type: bind
      - source: ./database
        target: /srv/database
        type: bind
      - source: ./library
        target: /srv/library
        type: bind
      - source: ./log/worker/user-service-queue
        target: /log
        type: bind
      - source: ./worker/user-service-queue
        target: /srv/worker/user-service-queue
        type: bind
      - source: ./tsconfig.json
        target: /srv/tsconfig.json
        type: bind
