
services:
  marketing:
    command: [ "yarn", "workspace", "@tw050x.net.service/marketing", "exec", "node", "--inspect=0.0.0.0:9229", "--watch", "artifact/serve.js" ]
    depends_on:
      assets:
        condition: service_healthy
      error:
        condition: service_healthy
      mongo-primary:
        condition: service_healthy
      traefik:
        condition: service_healthy
    develop:
      watch:
        - action: restart
          include:
            - "**/*.js"
          path: ./library/
        - action: restart
          include:
            - "**/*.js"
          path: ./service/marketing/artifact
    environment:
      - LOGS_LEVEL=info
      - LOGS_DIRECTORY=/log
      - MONGO_CLIENT_AUTH_PASSWORD=password
      - MONGO_CLIENT_AUTH_USERNAME=root
      - MONGO_CLIENT_REPLICA_SET=rs0
      - MONGO_CLIENT_URI=mongodb://mongo-primary:27017,mongo-secondary-a:27017
      - NODE_ENV=development
      - SESSIONS_DATABASE_NAME=sessions
      - SESSIONS_DATABASE_ACTIVITY_COLLECTION_NAME=activity
      - SESSIONS_DATABASE_LOGINS_COLLECTION_NAME=logins
      - USER_DATABASE_NAME=users
      - USER_DATABASE_CREDENTIALS_COLLECTION_NAME=credentials
      - USER_DATABASE_NONCES_COLLECTION_NAME=nonces
      - USER_DATABASE_PERMISSIONS_COLLECTION_NAME=permissions
      - USER_DATABASE_PROFILES_COLLECTION_NAME=profiles
    healthcheck:
      test: ["CMD-SHELL", "test -f /healthcheck && grep -q '^healthy$' /healthcheck"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    image: tw050x.net.service/marketing:latest
    labels:
      - traefik.docker.network=services
      - traefik.enable=true
      - traefik.http.routers.marketing.entrypoints=websecure
      - traefik.http.routers.marketing.middlewares=http-request-not-found-error@file
      - traefik.http.routers.marketing.rule=Host(`tw050x.dev`) && PathPrefix(`/`)
      - traefik.http.routers.marketing.priority=1
      - traefik.http.routers.marketing.tls=true
      - traefik.http.services.marketing.loadbalancer.server.port=3000
      - traefik.http.services.marketing.loadbalancer.server.scheme=https
      - traefik.http.services.marketing.loadbalancer.serversTransport=secure@file
    mem_limit: 512mb
    networks:
      mongo: {}
      services: {}
    ports:
      - "9203:9229"
    pull_policy: never
    volumes:
      - source: ./.configs
        target: /srv/.configs
        type: bind
      - source: ./.secrets
        target: /srv/.secrets
        type: bind
      - source: ./ca
        target: /srv/ca
        type: bind
      - source: ./certificates
        target: /srv/certificates
        type: bind
      - source: ./library
        target: /srv/library
        type: bind
      - source: ./log/service/marketing
        target: /log
        type: bind
      - source: ./service/marketing
        target: /srv/service/marketing
        type: bind
      - source: ./tsconfig.json
        target: /srv/tsconfig.json
        type: bind
