
services:

  localstack:
    env_file:
      - .env.service.localstack
    # image: localstack/localstack
    image: gresau/localstack-persist:4.10 # don't trust this
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    volumes:
      - source: ./service/localstack/data
        target: /persisted-data
        type: bind
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind

  mongo-primary:
    command: --replSet rs0 --keyFile /etc/mongo-keyfile --bind_ip_all
    depends_on:
      mongo-secondary-a:
        condition: service_healthy
    env_file:
      - .env.service.mongo
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    image: mongo:8.0.12
    ports:
      - 27017:27017
    restart: always
    volumes:
      - source: ./service/mongo/data/primary
        target: /data/db
        type: bind
      - read_only: true
        source: ./service/mongo/mongo-keyfile
        target: /etc/mongo-keyfile
        type: bind

  mongo-secondary-a:
    command: --replSet rs0 --keyFile /etc/mongo-keyfile --bind_ip_all
    env_file:
      - .env.service.mongo
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    image: mongo:8.0.12
    ports:
      - 27018:27017
    restart: always
    volumes:
      - source: ./service/mongo/data/secondary-a
        target: /data/db
        type: bind
      - read_only: true
        source: ./service/mongo/mongo-keyfile
        target: /etc/mongo-keyfile
        type: bind

  traefik:
    image: traefik:v3.3.2
    depends_on:
      traefik-socket:
        condition: service_healthy
    env_file:
      - .env.service.traefik
    healthcheck:
      test: ["CMD-SHELL", "traefik healthcheck --ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.rule=Host(`traefik.tw050x.dev`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls=true
    mem_limit: 200mb
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./service/traefik/compose.traefik.toml:/etc/traefik/traefik.toml
      - ./service/traefik/certificates:/root/certificates

  traefik-socket:
    image: tecnativa/docker-socket-proxy:0.3.0
    env_file:
      - .env.service.traefik
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://localhost:2375/version || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    mem_limit: 200mb
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
