
include:
  - compose.assets.yaml
  - compose.authorisation-service.yaml
  - compose.error-service.yaml
  - compose.marketing-service.yaml
  - compose.mongo-service.yaml
  - compose.navigation-service.yaml
  - compose.portal-service.yaml
  - compose.traefik-service.yaml
  - compose.user-service.yaml

networks:
  mongo-service:
    driver: bridge
    name: mongo-service
  portal-service:
    driver: bridge
    name: portal-service
  traefik-service:
    driver: bridge
    name: traefik-services
  user-service:
    driver: bridge
    name: user-service
  services:
    driver: bridge
    name: services
