
services:

  rabbitmq:
    env_file:
      - .env.service.rabbitmq
    hostname: rabbitmq
    image: rabbitmq:4.2.0-management-alpine
    networks:
      - services
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - source: ./service/rabbitmq/data
        target: /var/lib/rabbitmq
        type: bind
