
include:
  - compose.assets.yaml
  - compose.authorisation.yaml
  - compose.error.yaml
  - compose.marketing.yaml
  - compose.mongo.yaml
  - compose.navigation.yaml
  - compose.portal.yaml
  - compose.sessions.yaml
  - compose.traefik.yaml
  - compose.user.yaml

networks:
  mongo:
    driver: bridge
    name: mongo
  portal:
    driver: bridge
    name: portal
  sessions:
    driver: bridge
    name: sessions
  traefik:
    driver: bridge
    name: traefiks
  user:
    driver: bridge
    name: user
  services:
    driver: bridge
    name: services
