declare global {
  namespace NodeJS {
    interface ProcessEnv {
      ACCOUNT_DATABASE_NAME: string;
      ACCOUNT_DATABASE_ACCOUNT_COLLECTION_NAME: string;
      ACCOUNT_DATABASE_BILLING_COLLECTION_NAME: string;
      ACCOUNT_DATABASE_INVITATION_COLLECTION_NAME: string;
      ACCOUNT_DATABASE_MEMBERSHIP_COLLECTION_NAME: string;
      ACCOUNT_DATABASE_PROFILE_COLLECTION_NAME: string;
      ACCOUNT_DATABASE_TENANT_COLLECTION_NAME: string;
    }
  }
}
export {};
